name: add-labels
on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
      - name: Synchronize labels
        uses: julb/action-manage-label@6ab8797f08ad692a9c1983de9b7c70fecaa927cf # v1
        with:
          from: .github/config/labels.yml
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
